language: node_js
node_js:
  - "12.13.0"
script:
  - echo "deploying..."
install:
  - npm install -g firebase-tools
  - npm install
  - npm run build
after_success:
  - firebase deploy --project arise-event-team --token $FIREBASE_TOKEN
